network:
    type: "lora"
    linear: 16
    linear_alpha: 16
  
  save:
    dtype: float16
    save_every: 250
    max_step_saves_to_keep: 4
    push_to_hub: false
  
  datasets:
    - folder_path: "/home/gero/GitHub/ai-toolkit/pixel_art_training_dataset"
      caption_ext: "txt"
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution: [512]
  
  train:
    batch_size: 1
    steps: 2000
    gradient_accumulation_steps: 2
    train_unet: true
    train_text_encoder: false
    gradient_checkpointing: true
    noise_scheduler: "flowmatch"
    optimizer: "adamw8bit"
    lr: 1e-4
    
    # Added skip_first_sample to avoid potential memory issues during initialization
    skip_first_sample: true
    
    ema_config:
      use_ema: true
      ema_decay: 0.99
    
    dtype: bf16
  
  model:
    name_or_path: "black-forest-labs/FLUX.1-dev"
    is_flux: true
    quantize: true
    low_vram: true
    # Added these parameters to help with model loading
    revision: "main"
    use_safetensors: true
    
  sample:
    sampler: "flowmatch"
    sample_every: 250
    width: 512
    height: 512
    prompts:
      - "[trigger] a girl with blue hair wearing a red dress against a brown background"
      - "[trigger] a warrior princess with long flowing hair wielding a pixel sword, standing in a magical forest"
      - "[trigger] an adventurer exploring a retro-style dungeon with torches and treasure chests"
      - "[trigger] a cheerful merchant character standing in front of a pixel art shop with potions and equipment"
    neg: ""
    seed: 42
    walk_seed: true
    guidance_scale: 4
    sample_steps: 20